apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  name: hello-world
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/myproject/openjdk18
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
