apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  name: ruby-hello-world
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: 172.30.1.1:5000/my-project/ruby-hello-world:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""